---
editor: /usr/bin/vim
colorize: true
style: monokai
formatter: terminal16m
pager: /usr/bin/less -FR
cheatpaths:
  - name: community
    path: /root/.config/cheat/cheatsheets/community
    tags:
      - community
    readonly: true
  - name: personal
    path: /root/.config/cheat/cheatsheets/personal
    tags:
      - personal
    readonly: false
